# 101 Pandas Exercises for Data Analysis (Python)

## 1. How to import pandas and check the version?

Import pandas and check the version used.

Desired Output:

Your pandas version will be shown here
e.g., 2.1.0

In [3]:
import pandas as pd
import numpy as np
print(pd.__version__)

3.0.3


## 2. How to create a series from a list, numpy array and dict?

Create a pandas series from each of the items below: a list, numpy and a dictionary

Desired Output:

a    0
b    1
c    2
d    4
e    3

dtype: int64

In [4]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

print(pd.Series(mylist))
print(pd.Series(myarr))
print(pd.Series(mydict))

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: str
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## 3. How to convert the index of a series into a column of a dataframe?

Difficulty Level: L1

Convert the series ser into a dataframe with its index as another column on the dataframe.

Desired Output:

  index  0
0     a  0
1     b  1
2     c  2
3     d  4
4     e  3

In [5]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


## 4. How to combine many series to form a dataframe?

Difficulty Level: L1

Combine ser1 and ser2 to form a dataframe.

Desired Output:

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [ ]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution 1
df = pd.concat([ser1, ser2], axis=1)
df.columns = ['col1', 'col2']

# Solution 2
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4


## 5. How to assign name to the series’ index?

Difficulty Level: L1

Give a name to the series ser calling it ‘alphabets’.

Desired Output:

0    a
1    b
2    c
3    e
4    d

Name: alphabets, dtype: object

In [11]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = 'alphabets'

print(ser.head())

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: str


## 6. How to get the items of series A not present in series B?

Difficulty Level: L2

From ser1 remove items present in ser2.

Desired Output:

0    1
1    2
2    3
dtype: int64

In [16]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solution
print(ser1[~ser1.isin(ser2)])

0    1
1    2
2    3
dtype: int64


## 7. How to get the items not common to both series A and series B?

Difficulty Level: L2

Get all items of ser1 and ser2 not common to both.

Desired Output:

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [17]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solution to find symmetric difference
ser_u = pd.Series(np.union1d(ser1, ser2)) # find the union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # find the intersect
# from the union, remove the intersect to get the difference
print(ser_u[~ser_u.isin(ser_i)])

# or

only_in_ser1 = ser1[~ser1.isin(ser2)] # find the difference in ser1
only_in_ser2 = ser2[~ser2.isin(ser1)] # find the difference in ser2

# concatenate the two series to get the symmetric difference
result = pd.concat([only_in_ser1, only_in_ser2])

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


## 8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

Difficuty Level: L2 Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

Desired Output:

array([ -1.39,   6.49,  10.26,  13.07,  25.81])
# (exact values vary — output shows the 5 percentiles)

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))

# using numpy percentile method
print(np.percentile(ser, q=[0, 25, 50, 75, 100]).round(2))

# or

# using pandas quantile method
result = ser.quantile([0, 0.25, 0.5, 0.75, 1]).round(2).to_numpy()

result = ser.describe()[["min", "25%", "50%", "75%", "max"]].round(2)

print(result)

[ 0.02  6.7  11.14 12.79 19.05]
[ 0.02  6.7  11.14 12.79 19.05]


## 9. How to get frequency counts of unique items of a series?

Difficulty Level: L1

Calculate the frequency counts of each unique value ser.

Desired Output:

# Output shows value_counts, e.g.:
b    6
a    5
c    4
...
dtype: int64

In [27]:
# take the letters at the random 30 indices and create a series
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser.value_counts()

b    8
h    5
e    4
a    4
c    3
f    3
d    2
g    1
Name: count, dtype: int64

## 10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

Difficulty Level: L2

From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.

Desired Output:

Top 2 Freq: 4    5
3    3
...

0     Other
1     Other
2         3
...

In [ ]:
np.random.seed(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

top_2 = ser.value_counts().index[:2] # get the top 2 frequent values

result = ser.where(ser.isin(top_2), "Other")

print("Top 2 Freq:", top_2)

print(result)

Top 2 Freq: Index([1, 4], dtype='int64')
0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object


## 11. How to bin a numeric series to 10 groups of equal size?

Difficulty Level: L2

Bin the series ser into 10 equal deciles and replace the values with the bin name.

Desired Output:

0    0.556912
1    0.892955
...
dtype: float64

0    7th
1    9th
...
dtype: category
Categories (10, object): [1st < 2nd < 3rd < ... < 9th < 10th]

In [ ]:
ser = pd.Series(np.random.random(20))

# Solution
# quartile binning is done using qcut where the bins have equal counts of data points.
print(pd.qcut(ser, q=10, 
labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head())

0     8th
1     7th
2     7th
3    10th
4     4th
dtype: category
Categories (10, str): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']


## 12. How to convert a numpy array to a dataframe of given shape? (L1)

Difficulty Level: L1

Reshape the series ser into a dataframe with 7 rows and 5 columns

Desired Output:

    0  1  2  3  4
0   1  2  1  2  5
1   1  2  4  5  2
2   1  3  3  2  8
3   8  6  4  9  6
4   2  1  1  8  5
5   3  2  8  5  6
6   1  5  5  4  6

(values vary — output is a 7x5 DataFrame)

In [62]:
ser = pd.Series(np.random.randint(1, 10, 35))

# Solution
df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  9  5  6  8  7
1  1  6  4  4  8
2  4  9  8  1  3
3  5  2  2  6  1
4  7  4  4  8  6
5  9  9  7  3  4
6  5  6  4  6  5


## 13. How to find the positions of numbers that are multiples of 3 from a series?

Difficulty Level: L2

Find the positions of numbers that are multiples of 3 from ser.

Desired Output:

0    6
1    8
...
dtype: int64

array([[0],
       [2],
       [4]])
       
# (positions where values are multiples of 3)

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))

mask = ser % 3 == 0

result = ser[mask].index.to_numpy()

print(result)

# or

np.argwhere(ser % 3 == 0).flatten() # returns a 2D array of indices where the condition is True



[0 1 2 3 4 5]


## 14. How to extract items at given positions from a series

Difficulty Level: L1

From ser, extract the items at positions in list pos.

Desired Output:

0     a
4     e
8     i
14    o
20    u
dtype: object

In [77]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

print(ser.take(pos)) # returns a series with the values at the given positions

0     a
4     e
8     i
14    o
20    u
dtype: str


## 15. How to stack two series vertically and horizontally ?

Difficulty Level: L1

Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# vertical concatenation of two series to form a longer series
print(pd.concat([ser1, ser2]))

# horizontal concatenation of two series to form a dataframe
pd.concat([ser1, ser2], axis=1)

,0,1
0,0,a
1,1,b
2,2,c
3,3,d
4,4,e


## 17. How to compute the mean squared error on a truth and predicted series?

Difficulty Level: L2

Compute the mean squared error of truth and pred series.

In [ ]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# MSE used in ML regression models.
# Common regression metric to evaluate the performance of a model. 
# It is the average of the squared differences between the predicted and actual values.
# This metric is used to measure how close a regression line is to a set of points.
# lower MSE = better model performance, higher MSE = worse model performance.


difference = truth - pred 
squared_difference = difference ** 2
mse = squared_difference.mean()

print(mse)


0.19638407108055342


## 20. How to compute difference of differences between consequtive numbers of a series?

Difficulty Level: L1

Difference of differences between the consequtive numbers of ser.

Desired Output:

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [80]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


## 21. How to convert a series of date-strings to a timeseries?

Difficiulty Level: L2

Desired Output:

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00

dtype: datetime64[ns]

In [96]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 
pd.to_datetime(ser, format="mixed")

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[us]

## 22. How to get the day of month, week number, day of year and day of week from a series of date strings?

Difficulty Level: L2 Get the day of month, week number, day of year and day of week from ser.

In [97]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution
ser_ts = pd.to_datetime(ser, format="mixed")

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.isocalendar().week.tolist())

# day of year
print("Day num of year: ", ser_ts.dt.dayofyear.tolist())

# day of week
print("Day of week: ", ser_ts.dt.day_name().tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


## 23. How to convert year-month string to dates corresponding to the 4th day of the month?

Difficulty Level: L2 Change ser to dates that start with 4th of the respective months.

Desired Output:

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [100]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

result = pd.to_datetime("04 " + ser)

print(result)


0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[us]


## 26. How to get the mean of a series grouped by another series?

Difficiulty Level: L2 Compute the mean of weights of each fruit.

In [102]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

print(weights.groupby(fruit).mean())

df = pd.DataFrame({
    "fruit": fruit,
    "weight": weights
})

result = df.groupby("fruit")["weight"].mean()

print(result)

apple     5.75
banana    9.00
carrot    4.60
dtype: float64
fruit
apple     5.75
banana    9.00
carrot    4.60
Name: weight, dtype: float64
